stages:
  - build
  - test
  - deploy

build-backend:
    stage: build
    image: docker:stable
    services:
    - docker:dind
    script:
    - cd ./iighoiijm-be
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/ramonfabrega/idb/backend -f ./src/Dockerfile .
    - docker push registry.gitlab.com/ramonfabrega/idb/backend

test-backend:
    image: registry.gitlab.com/ramonfabrega/idb/backend
    stage: test
    script:
    - ls -al
    - cd ./iighoiijm-be
    - make test
